### ISSUE TITLE
[FEATURE] - Décortiquer-devise

### ISSUE THREAD

**Issue by Slashflex** [Kercode/tutti_gruppi#29]
**Contexte**

Décortiquer la documentation et pratiquer à l'aide de la gem devise

**Demande**

Découvrir et prendre main la gem devise
source :
- [Gem Devise](https://github.com/plataformatec/devise)
- [Tuto Authentification](https://guides.railsgirls.com/devise)

**Liste des tâches**

Liste des tâches à effectuer dans cette ordre pour mener à bien cette feature:
- [x] Lire la documentation
- [x] Pratiquer au travers d'un projet test

**Comment by ghost** [comment]
Nous avons lu et pratiqué sur un projet test en suivant:
- [cette vidéo](https://www.youtube.com/watch?v=rIGPVEAeA6M&t=1140s)
- [doc github](https://github.com/plataformatec/devise)

On a pu voir:
- Création de compte
- validation par email
- si l'utilisateur ne reçoit pas l'email où qu'il a supprimé par erreur, il peut redemander un mail de confirmation
- connexion / déconnexion
- connexion avec login OU email
- envoyer un email en cas d'oublie de password pour le modifier grâce à un lien
- gestion d'erreur (mauvais login ou password OU en attente de confirmation)
- option remember me
- application validates / regex
- ajout de champs dans les formulaires
- modifications des formulaires
